### ISSUE TITLE
Wrong operator

### ISSUE THREAD

**Issue by serkanaslan34** [Hona/UpBlazor#38]
Hi there, 
Could you check this code in RedirectToLogin.razor.
You are checking IsAuthenticated. but when it return true your method redirect to "access-denied" page or am i wrong ? 
` 
        if (user.Identity?.IsAuthenticated ?? false)
        {
            _navigationManager.NavigateTo("/access-denied");
            return;
        }`

**Comment by Hona** [comment]
Hi,

If the user is already logged in - it is unauthorized to login again.

Hence the redirect.

Thanks!
