### ISSUE TITLE
Import 2Up Savers for use with budgeting

### ISSUE THREAD

**Issue by thesammykins** [Hona/UpBlazor#44]
Hey! Firstly, amazing tool! Will be experimenting with using this over my existing Excel spreadsheet 😂

So, my partner and I split our bills into 2Up Savers that we run, which don't seem to get imported by your tool for me to actually add in? Without those I actually can't correctly add in a complete budget picture (I wish I could get as rich as it tells me!)

No rush, I know this is clearly a hobby thing for you but thought I'd put the idea into the air for the future of the project! Good luck :)

**Comment by Hona** [comment]
Hey @thesammykins, Thanks for raising the issue!

So... as far as I know the API for getting a list of accounts, should receive all the 2up & up accounts. However, I will do a bit of investigation myself.

Few docs: 
https://developer.up.com.au/#get_accounts
https://github.com/up-banking/api/issues/31#issuecomment-1008441619

I'll keep you posted :)

Also - I'd love any feedback you might have as as far as I know I'm the only one using my tool 😂

**Comment by thesammykins** [comment]
Awesome, yeah it seemed like it wasn't pulling all of the savers when I tried using it (I ended up doing some math in Excel but I wanted something that adjusted more frequently from API data)

I might raise a couple of other issues related to some oddities (mainly some UX stuff)

**Comment by Hona** [comment]
That would be great! Please raise tonnes of issues.  I believe I've fixed your problem with some missing accounts, I'll let you know

**Comment by Hona** [comment]
@thesammykins This should be fixed now - please retest and let me know :)

**Comment by thesammykins** [comment]
Something may be broken? Does it across multiple browsers :/

![image](https://user-images.githubusercontent.com/26049947/217402881-bb04bcc7-dd17-4a42-9ab1-5dac8b26f096.png)

`Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      HTTP Response: 
      
      "An unexpected error occurred."
      
      UpBlazor.ApiClient.ApiException: The HTTP status code of the response was not expected (500).
      
      Status: 500
      Response: 
      "An unexpected error occurred."
         at UpBlazor.ApiClient.ForecastClient.GetTotalsForecastAsync(Nullable`1 totalDays, CancellationToken cancellationToken)
         at UpBlazor.WebUI.Pages.Insights.Forecast.Index.ReloadAsync()
         at UpBlazor.WebUI.Pages.Insights.Forecast.Index.OnInitializedAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
HTTP Response: 

"An unexpected error occurred."

UpBlazor.ApiClient.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
"An unexpected error occurred."
   at UpBlazor.ApiClient.ForecastClient.GetTotalsForecastAsync(Nullable`1 totalDays, CancellationToken cancellationToken)
   at UpBlazor.WebUI.Pages.Insights.Forecast.Index.ReloadAsync()
   at UpBlazor.WebUI.Pages.Insights.Forecast.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
_bound_js_globalThis_console_error @ _bound_js_globalThis_console_error:7
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_get_response_length @ _bound_js_INTERNAL_http_wasm_get_response_length:8
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_fetch @ _bound_js_INTERNAL_http_wasm_fetch:14
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_get_response_length @ _bound_js_INTERNAL_http_wasm_get_response_length:8
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_fetch @ _bound_js_INTERNAL_http_wasm_fetch:14
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_get_response_length @ _bound_js_INTERNAL_http_wasm_get_response_length:8
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_fetch @ _bound_js_INTERNAL_http_wasm_fetch:14
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_bound @ 008ea256:0x1bb968
Module._mono_wasm_invoke_method_bound @ dotnet.7.0.2.yq23ij5n5i.js:14
Ws @ dotnet.7.0.2.yq23ij5n5i.js:5
b.javaScriptExports.complete_task @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
Kr @ dotnet.7.0.2.yq23ij5n5i.js:5
_bound_js_INTERNAL_http_wasm_fetch @ _bound_js_INTERNAL_http_wasm_fetch:14
Ss @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x17f39
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x18004
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x18004
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x18004
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x18004
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
BINDINGS_SetTaskSourceResultRef @ BINDINGS_SetTaskSourceResultRef:27
Ki.t.<computed> @ dotnet.7.0.2.yq23ij5n5i.js:5
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
Promise.then (async)
si @ dotnet.7.0.2.yq23ij5n5i.js:5
Qs @ dotnet.7.0.2.yq23ij5n5i.js:5
Xs @ dotnet.7.0.2.yq23ij5n5i.js:5
Ke._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.yq23ij5n5i.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.yq23ij5n5i.js:14
$func190 @ 008ea256:0x18004
$func160 @ 008ea256:0x17436
$func98 @ 008ea256:0x6fea
$func97 @ 008ea256:0x5e8f
$func7587 @ 008ea256:0x18c12c
$func1618 @ 008ea256:0x71e98
$func1623 @ 008ea256:0x725c1
$func1650 @ 008ea256:0x74670
$mono_wasm_invoke_method_ref @ 008ea256:0x1bb9fe
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.yq23ij5n5i.js:14
_UpBlazor_WebUI__entrypoint @ _UpBlazor_WebUI__entrypoint:26
(anonymous) @ dotnet.7.0.2.yq23ij5n5i.js:5
ji @ dotnet.7.0.2.yq23ij5n5i.js:5
callEntryPoint @ blazor.webassembly.js:1
Vt @ blazor.webassembly.js:1
await in Vt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1`

**Comment by Hona** [comment]
Yeah... I think I pushed out a buggy version that caused an endpoint to be spammed... your API token might be rate limited for a little bit. I need to make it show that more evidently though

**Comment by Hona** [comment]
>  1000 requests globally per access token per hour

You can recreate your access token then update it, or wait an hour

**Comment by thesammykins** [comment]
Yep my API token definitely seems rate limited. I'll try re-gen it.

`PUT https://upblazor-webapi.azurewebsites.net/api/up/token 400 (Bad Request)`

**Comment by Hona** [comment]
@thesammykins can you try regenerating it again please - theres a chance it is a copy paste error, but the site should be more descriptive now

**Comment by thesammykins** [comment]
Mint, working now and can see all the 2Ups, would be extra bonus to mark them as 2Up specific savers, but think the API just dumps them with no way to differentiate between?

**Comment by Hona** [comment]
Hmm. The API doesn't tell you however I can add a hack to differentiate. It's worth doing so I'll let you know when that change is ready

**Comment by Hona** [comment]
@thesammykins  Done - let me know if it looks good to you, and if so I think we can close this issue

**Comment by thesammykins** [comment]
That 100% works, perfect!
