### ISSUE TITLE
[UX] Recurring expense doesn't have a month selector

### ISSUE THREAD

**Issue by thesammykins** [Hona/UpBlazor#46]
When creating recurring expenses, the only way to select 'monthly' is to either decide on 30 or 31 days which isn't accurate. It should probably be done daily, weekly, fortnightly, monthly, yearly with amount selection for each e.g. 1 monthly, 2 monthly/1 year, 2 years, etc.

At the moment for yearly expenses you have to select 365 days as another example, would be nicer to just be 1 Year.

I think this might be throwing out forecasting in the long term, so probably something worthwhile looking at since it will have a profound effect on what you see over a 365 day period.

**Comment by Hona** [comment]
This is done now - added 'months' to all interval selectors. Let me know of any problems, but I will be testing myself
